### ISSUE TITLE
Openpose body25

### ISSUE THREAD

**Issue by tiamo405** [sangyun884/HR-VITON#26]
When making the code, I want to use my poses that I created myself, but online it's mostly 18 point bodies. I want the output like the article, what code should I use. thank you

**Comment by martacosano** [comment]
Hello @tiamo405 ! you can use OpenPose with configuration BODY_25 (25 keypoints) to extract the pose, instead of coco (18 keypoints).Here there's a photo of both configurations: https://www.researchgate.net/figure/Architecture-of-the-different-modules-to-recognise-poses-and-control-the-robot_fig3_340618434

**Comment by tuyendb** [comment]
> 

could u give me github url ?

**Comment by koo616** [comment]
Hello guys.
You can check the detailed command line operation I used for the openpose. Please check it :)
